class_name GTLanguage
extends RefCounted
const KOREAN={
 "CHASE":"추적", "BUMPER":"범퍼", "HOOD":"후드", "COCKPIT":"조종석", "ORBIT":"자유 회전",
 "Graphics": "그래픽",
 "Rendering controls are independent of vehicle performance.": "화면 품질 설정은 차량 성능과 별도로 적용됩니다.",
 "Quality preset": "화면 품질",
 "Low": "낮음",
 "Medium": "중간",
 "High": "높음",
 "Ultra": "최고",
 "Render scale": "렌더링 배율",
 "Anti-aliasing": "계단 현상 완화",
 "Off": "끄기",
 "On": "켜기",
 "Shadow quality": "그림자 품질",
 "512 / hard": "512 · 선명",
 "1024 / soft": "1024 · 부드럽게",
 "2048 / soft": "2048 · 부드럽게",
 "4096 / soft": "4096 · 부드럽게",
 "Shadow distance · m": "그림자 거리 · m",
 "Reflections": "반사",
 "Sky": "하늘",
 "Screen space": "화면 공간 반사",
 "Screen space / high": "화면 공간 반사 · 높음",
 "Vegetation density": "식생 밀도",
 "Traffic count": "교통 차량 수",
 "Particles": "입자 효과",
 "Post-processing": "후처리",
 "Rear-view mirror": "후방 미러",
 "Frame limit": "초당 프레임 제한",
 "Unlimited": "제한 없음",
 "VSync": "수직 동기화",
 "Fullscreen": "전체 화면",
 "Window resolution": "창 해상도",
 "Save settings": "설정 저장",
 "Graphics preferences saved": "그래픽 설정을 저장했습니다.",
 "Camera & audio": "카메라·소리",
 "Camera": "카메라",
 "Field of view": "시야각",
 "Horizontal offset": "좌우 위치",
 "Vertical offset": "높이",
 "Forward / rear offset": "앞뒤 위치",
 "Camera vibration": "카메라 흔들림",
 "멀미 감소 / Reduced motion": "멀미 감소",
 "Mute audio": "음소거",
 "Speed in mph": "속도 단위: 마일/시",
 "Save camera settings": "카메라 설정 저장",
 "Camera saved": "카메라 설정을 저장했습니다.",
 "Chase": "추적",
 "Bumper": "범퍼",
 "Hood": "후드",
 "Cockpit": "조종석",
 "Orbit": "자유 회전",
 "PAINT FINISH": "차체 색상",
 "Vehicle setup": "차량 설정",
 "Take it for a drive                    →": "주행 시작  →",
 "User-supplied 992 GT3 R model. Physics-driven wheels, brake discs, steering and suspension.": "992 GT3 R · 물리 기반 바퀴·브레이크·조향·서스펜션",
 "Estimates vary with surface, gearing and driving aids.": "예상 성능은 노면·기어비·운전 보조에 따라 달라집니다.",
 "POWER": "출력",
 "TORQUE": "토크",
 "MASS": "질량",
 "DRIVE": "구동",
 "CLEAR": "맑음",
 "OVERCAST": "흐림",
 "RAIN": "비",
 "DAY": "낮",
 "GOLDEN HOUR": "노을",
 "NIGHT": "밤",
 "THROTTLE": "가속",
 "BRAKE": "브레이크",
 "CLUTCH": "클러치",
 "FREE DRIVE": "자유 주행",
 "HIGH SPEED": "고속 주행",
 "TIME TRIAL": "시간 기록",
 "CHECKPOINTS": "체크포인트",
 "Primary": "기본 키",
 "Secondary": "보조 키",
 "Throttle 0–1": "가속 0–1",
 "Brake 0–1": "브레이크 0–1",
 "Steering −1–1": "조향 −1–1"
}
static func text(value: String) -> String:
 if GTControls.language=="ko":return KOREAN.get(value,value)
 return value
