from pathlib import Path
p=Path(r'C:/Users/admin/Documents/Codex/2026-09-08/fable-5-1-vs-fable-at-4/outputs/AsterGT')
f=p/'scripts/car.gd';s=f.read_text(encoding='utf8')
s=s.replace('  wheel_radii.append(radius)','  if vehicle_rig.has("mounts"):\n   var fixed_mount=vehicle_rig.mounts[tag];mount=Vector3(fixed_mount[0],fixed_mount[1],fixed_mount[2])\n  wheel_radii.append(radius)')
f.write_text(s,encoding='utf8')
f=p/'scripts/main.gd';s=f.read_text(encoding='utf8')
s=s.replace('func save_preferences() -> void:\n if automation_run:return','func save_preferences() -> bool:\n if automation_run:return true')
s=s.replace(' if err!=OK or cfg_error!=OK:hud.notify("설정 저장 실패: "+error_string(err if err!=OK else cfg_error))',' if err!=OK or cfg_error!=OK:\n  hud.notify("설정 저장 실패: "+error_string(err if err!=OK else cfg_error));return false\n return true')
f.write_text(s,encoding='utf8')
f=p/'scripts/hud.gd';s=f.read_text(encoding='utf8')
s=s.replace('func():game.save_preferences();notify("Graphics preferences saved")','func():\n  if game.save_preferences():notify("Graphics preferences saved"))'[:-1])
s=s.replace('var err=game.cam.save_settings();game.save_preferences();notify("Camera saved" if err==OK else "저장 실패: "+error_string(err))','var err=game.cam.save_settings();var prefs_ok=game.save_preferences();\n  if err!=OK:notify("저장 실패: "+error_string(err))\n  elif prefs_ok:notify("Camera saved")')
f.write_text(s,encoding='utf8')
print('fixed model hardpoints and save failure messages applied')
