from pathlib import Path
p=Path('outputs/AsterGT')
f=p/'scripts/main.gd';s=f.read_text(encoding='utf-8').replace('"shadows":175.0','"shadow_quality":2,"shadows":175.0').replace('graphics.preset=i;graphics.scale=','graphics.preset=i;graphics.shadow_quality=i;graphics.scale=')
s=s.replace('world.sun.shadow_enabled=graphics.shadows>0;', '''RenderingServer.directional_shadow_atlas_set_size([512,1024,2048,4096][clampi(graphics.shadow_quality,0,3)],true)
 RenderingServer.directional_soft_shadow_filter_set_quality(clampi(graphics.shadow_quality,0,3))
 world.sun.shadow_enabled=graphics.shadows>0;''')
s=s.replace('"preset":[0,3],"scale"','"preset":[0,3],"shadow_quality":[0,3],"scale"');f.write_text(s,encoding='utf-8')
f=p/'scripts/hud.gd';s=f.read_text(encoding='utf-8').replace('slider(col,"Shadow distance · m",','option(col,"Shadow quality",["512 / hard","1024 / soft","2048 / soft","4096 / soft"],game.graphics.shadow_quality,func(i):game.graphics.shadow_quality=i;game.apply_graphics())\n slider(col,"Shadow distance · m",');f.write_text(s,encoding='utf-8')
f=p/'tests/integration_test.gd';s=f.read_text(encoding='utf-8').replace('game.hud.page=="home"','game.hud.page=="home" and game.hud.menu_root.find_children("*","Button",true,false).size()==6')
s=s.replace(' game.car.controls_enabled=false;game.car.freeze=true',''' game.start_drive("Free Drive");game.car.test_input={"brake":1.0};await frames(120)
 var wall=StaticBody3D.new();game.add_child(wall);wall.transform=game.car.global_transform;wall.position+=game.car.global_basis.z*4
 var shape=BoxShape3D.new();shape.size=Vector3(12,8,.2);var collider=CollisionShape3D.new();collider.shape=shape;wall.add_child(collider);await frames(4)
 game.cam.mode=0;game.cam.menu_preview=false;game.cam.first=true;game.cam.update(.016)
 check("chase_camera_stops_before_wall",game.car.to_local(game.cam.camera.global_position).z<3.95)
 wall.queue_free();await frames(2)
 game.car.controls_enabled=false;game.car.freeze=true''')
s=s.replace('game.apply_preset(2)\n results','check("render_scale_applied",absf(game.get_viewport().scaling_3d_scale-loads[3].scale)<.01)\n game.apply_preset(2)\n results');f.write_text(s,encoding='utf-8')
f=p/'tests/dynamics_test.gd';s=f.read_text(encoding='utf-8')
a=s.index(' # Engine-side changes')
s=s[:a]+''' # Inclined surface: neutral rollback, parking lock, uphill launch.
 var hill=StaticBody3D.new();hill.position=Vector3(1000,0,0);hill.rotation.x=deg_to_rad(8);scene.add_child(hill)
 var hill_shape=BoxShape3D.new();hill_shape.size=Vector3(30,1,100);var hill_col=CollisionShape3D.new();hill_col.shape=hill_shape;hill.add_child(hill_col)
 await reset();car.recover(Transform3D(Basis(Vector3.RIGHT,deg_to_rad(8)),Vector3(1000,4.7,-25)));car.test_input={"brake":1.0};await frames(240)
 check("slope_four_wheel_contact",car.grounded==4)
 car.set_selector("N");car.test_input={};await frames(240)
 check("neutral_rolls_downhill",car.forward_speed<-.5)
 car.test_input={"brake":1.0};await frames(240);var parked=car.set_selector("P");var hill_origin=car.position;car.test_input={};await frames(480)
 results.measurements["slope_park_drift_m"]=car.position.distance_to(hill_origin)
 check("park_holds_on_8_degree_slope",parked and car.position.distance_to(hill_origin)<.15)
 car.set_selector("D");car.test_input={"throttle":.9};await frames(240)
 check("uphill_launch",car.forward_speed>1.0)
 # Rigid collision and continuous collision detection at 100 km/h.
 await reset(100)
 var wall=StaticBody3D.new();wall.position=Vector3(0,2,-30);scene.add_child(wall)
 var wall_shape=BoxShape3D.new();wall_shape.size=Vector3(20,4,.5);var wall_col=CollisionShape3D.new();wall_col.shape=wall_shape;wall.add_child(wall_col)
 await frames(240)
 check("collision_does_not_tunnel",car.position.z> -31 and car.position.is_finite())
 check("collision_reduces_speed",car.speed_kph<50)
''' +s[a:];f.write_text(s,encoding='utf-8')
